package com.krtpromanager.krtpromanagerSpringBoot.repository;

import com.krtpromanager.krtpromanagerSpringBoot.entity.DetalleCampeonatoCategoriaCompetidor;
import org.springframework.data.jpa.repository.JpaRepository;

public interface DetalleCampeonatoCategoriaCompetidorRepository extends JpaRepository<DetalleCampeonatoCategoriaCompetidor, Long> {
}