# Generated by Django 5.0.6 on 2024-06-30 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('local', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('provincia', models.CharField(blank=True, max_length=255, null=True)),
                ('url_bases', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'campeonato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('genero', models.CharField(blank=True, max_length=255, null=True)),
                ('grado', models.CharField(blank=True, max_length=255, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Competidor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'competidor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallecampeonatocategoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detallecampeonatocategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallecampeonatocategoriacompetidor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detallecampeonatocategoriacompetidor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dojo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombredojo', models.CharField(db_column='nombreDojo', max_length=255)),
                ('senseidojo', models.CharField(db_column='senseiDojo', max_length=255)),
            ],
            options={
                'db_table': 'dojo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sancion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('apellidos', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallecategoriacompetidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelocompleto.categoria')),
                ('competidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelocompleto.competidor')),
            ],
            options={
                'db_table': 'detallecategoriacompetidor',
                'unique_together': {('categoria', 'competidor')},
            },
        ),
    ]
