# Generated by Django 5.0.6 on 2024-06-30 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre para el loginnnnnn')),
                ('nombres', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('academia', 'Academia'), ('arbitro', 'Arbitro')], default='academia', max_length=20)),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField()),
                ('local', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('url_bases', models.FileField(blank=True, null=True, upload_to='')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'Campeonato',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A7', 'A7'), ('A8', 'A8'), ('A9', 'A9'), ('A10', 'A10'), ('A11', 'A11'), ('A12', 'A12'), ('A13', 'A13'), ('A14', 'A14'), ('A15', 'A15'), ('A16', 'A16'), ('A17', 'A17'), ('A18', 'A18'), ('A19', 'A19'), ('A20', 'A20'), ('A21', 'A21'), ('A22', 'A22'), ('A23', 'A23'), ('A24', 'A24'), ('A25', 'A25'), ('A26', 'A26'), ('A27', 'A27'), ('A28', 'A28'), ('A29', 'A29'), ('A30', 'A30'), ('A31', 'A31'), ('A32', 'A32'), ('A33', 'A33'), ('A34', 'A34'), ('A35', 'A35'), ('A36', 'A36'), ('A37', 'A37'), ('A38', 'A38'), ('A39', 'A39'), ('A40', 'A40'), ('A41', 'A41'), ('A42', 'A42'), ('A43', 'A43'), ('A44', 'A44'), ('A45', 'A45'), ('A46', 'A46'), ('A47', 'A47'), ('A48', 'A48'), ('A49', 'A49'), ('A50', 'A50'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'), ('B6', 'B6'), ('B7', 'B7'), ('B8', 'B8'), ('B9', 'B9'), ('B10', 'B10'), ('B11', 'B11'), ('B12', 'B12'), ('B13', 'B13'), ('B14', 'B14'), ('B15', 'B15'), ('B16', 'B16'), ('B17', 'B17'), ('B18', 'B18'), ('B19', 'B19'), ('B20', 'B20'), ('B21', 'B21'), ('B22', 'B22'), ('B23', 'B23'), ('B24', 'B24'), ('B25', 'B25'), ('B26', 'B26'), ('B27', 'B27'), ('B28', 'B28'), ('B29', 'B29'), ('B30', 'B30'), ('B31', 'B31'), ('B32', 'B32'), ('B33', 'B33'), ('B34', 'B34'), ('B35', 'B35'), ('B36', 'B36'), ('B37', 'B37'), ('B38', 'B38'), ('B39', 'B39'), ('B40', 'B40'), ('B41', 'B41'), ('B42', 'B42'), ('B43', 'B43'), ('B44', 'B44'), ('B45', 'B45'), ('B46', 'B46'), ('B47', 'B47'), ('B48', 'B48'), ('B49', 'B49'), ('B50', 'B50')], max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
                ('grado', models.CharField(max_length=50)),
                ('modalidad', models.CharField(choices=[('Kata', 'Kata'), ('Kumite', 'Kumite')], max_length=10)),
            ],
            options={
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Competidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10)),
            ],
            options={
                'db_table': 'Competidor',
            },
        ),
        migrations.CreateModel(
            name='DetalleCampeonatoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelocompleto.campeonato')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelocompleto.categoria')),
            ],
            options={
                'db_table': 'DetalleCampeonatoCategoria',
                'unique_together': {('campeonato', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='DetalleCampeonatoCategoriaCompetidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelocompleto.detallecampeonatocategoria')),
                ('competidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelocompleto.competidor')),
            ],
            options={
                'db_table': 'DetalleCampeonatoCategoriaCompetidor',
                'unique_together': {('categoria_campeonato', 'competidor')},
            },
        ),
        migrations.CreateModel(
            name='Dojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDojo', models.CharField(blank=True, max_length=150, null=True)),
                ('senseiDojo', models.CharField(blank=True, max_length=120, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Dojo',
            },
        ),
        migrations.AddField(
            model_name='competidor',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelocompleto.dojo'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='dojo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelocompleto.dojo'),
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
                ('detallecampeonatocategoriacompetidor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelocompleto.detallecampeonatocategoriacompetidor')),
            ],
            options={
                'db_table': 'Sancion',
            },
        ),
        migrations.CreateModel(
            name='DetalleCategoriaCompetidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelocompleto.categoria')),
                ('competidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelocompleto.competidor')),
            ],
            options={
                'db_table': 'DetalleCategoriaCompetidor',
                'unique_together': {('categoria', 'competidor')},
            },
        ),
    ]
