# Generated by Django 5.0.6 on 2024-06-02 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre para el loginnnnnn')),
                ('nombres', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('academia', 'Academia'), ('arbitro', 'Arbitro')], default='academia', max_length=20)),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField()),
                ('local', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('url_bases', models.FileField(blank=True, null=True, upload_to='campeonatos/')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('A41', 'A41'), ('A42', 'A42'), ('A43', 'A43'), ('B41', 'B41'), ('B42', 'B42'), ('B43', 'B43')], max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
                ('grado', models.CharField(max_length=50)),
                ('modalidad', models.CharField(choices=[('Kata', 'Kata'), ('Kumite', 'Kumite')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Competidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCampeonatoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelocompleto.campeonato')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelocompleto.categoria')),
            ],
            options={
                'unique_together': {('Campeonato', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='DetalleCampeonatoCategoriaCompetidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelocompleto.detallecampeonatocategoria')),
                ('competidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelocompleto.competidor')),
            ],
            options={
                'unique_together': {('categoria_campeonato', 'competidor')},
            },
        ),
        migrations.CreateModel(
            name='Dojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDojo', models.CharField(blank=True, max_length=150, null=True)),
                ('senseiDojo', models.CharField(blank=True, max_length=120, null=True)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='competidor',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelocompleto.dojo'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='dojo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelocompleto.dojo'),
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
                ('competidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelocompleto.detallecampeonatocategoriacompetidor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCategoriaCompetidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelocompleto.categoria')),
                ('competidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelocompleto.competidor')),
            ],
            options={
                'unique_together': {('categoria', 'competidor')},
            },
        ),
    ]
