# Generated by Django 5.0.6 on 2024-06-23 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelocompleto', '0002_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
