# Generated by Django 5.0.6 on 2024-06-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelocompleto', '0003_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
